/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.noscale.ecashier.views;

import com.noscale.ecashier.controllers.MainController;
import com.noscale.ecashier.views.MainFrame;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JSeparator;
import javax.swing.JTextField;

/**
 *
 * @author rizkikurniawan
 */
public class LoginFrame extends javax.swing.JFrame {

    private MainFrame mainFrame;
    /**
     * Creates new form LoginForm
     */
    public LoginFrame() {
        initComponents();
        mainFrame = new MainFrame();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public MainFrame getMainFrame() {
        return mainFrame;
    }

    public JLabel getCloseTxt() {
        return closeTxt;
    }

    public JButton getLoginButton() {
        return loginButton;
    }

    public JPanel getOverlayPanel() {
        return overlayPanel;
    }

    public JPasswordField getPasswordField() {
        return passwordField;
    }

    public JSeparator getPasswordSeparator() {
        return passwordSeparator;
    }

    public JLabel getPasswordTxt() {
        return passwordTxt;
    }

    public JTextField getUsernameField() {
        return usernameField;
    }

    public JSeparator getUsernameSeparator() {
        return usernameSeparator;
    }

    public JLabel getUsernameTxt() {
        return usernameTxt;
    }

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        usernameSeparator = new javax.swing.JSeparator();
        passwordSeparator = new javax.swing.JSeparator();
        passwordField = new javax.swing.JPasswordField();
        closeTxt = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        passwordTxt = new javax.swing.JLabel();
        usernameTxt = new javax.swing.JLabel();
        overlayPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(57, 113, 147));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Please call administrator if you forgot password");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        usernameField.setBackground(new java.awt.Color(57, 113, 147));
        usernameField.setForeground(new java.awt.Color(255, 255, 255));
        usernameField.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        usernameField.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel3.add(usernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 270, 20));

        usernameSeparator.setForeground(new java.awt.Color(57, 113, 200));
        jPanel3.add(usernameSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 270, 10));

        passwordSeparator.setBackground(new java.awt.Color(57, 113, 200));
        passwordSeparator.setForeground(new java.awt.Color(57, 113, 200));
        jPanel3.add(passwordSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 270, 10));

        passwordField.setBackground(new java.awt.Color(57, 113, 147));
        passwordField.setForeground(new java.awt.Color(255, 255, 255));
        passwordField.setBorder(null);
        passwordField.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel3.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 270, 20));

        closeTxt.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        closeTxt.setForeground(new java.awt.Color(57, 113, 177));
        closeTxt.setText("X");
        jPanel3.add(closeTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        loginButton.setBackground(new java.awt.Color(126, 87, 194));
        loginButton.setForeground(new java.awt.Color(255, 255, 255));
        loginButton.setText("Login");
        loginButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 270, 30));

        passwordTxt.setBackground(new java.awt.Color(57, 113, 200));
        passwordTxt.setForeground(new java.awt.Color(57, 113, 200));
        passwordTxt.setText("Password");
        jPanel3.add(passwordTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        usernameTxt.setForeground(new java.awt.Color(255, 255, 255));
        usernameTxt.setText("Username");
        jPanel3.add(usernameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 333, 420));

        overlayPanel.setBackground(new java.awt.Color(0, 0, 204));
        overlayPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(overlayPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 420));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/noscale/ecashier/assets/rsz_store.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel closeTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton loginButton;
    private javax.swing.JPanel overlayPanel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JSeparator passwordSeparator;
    private javax.swing.JLabel passwordTxt;
    private javax.swing.JTextField usernameField;
    private javax.swing.JSeparator usernameSeparator;
    private javax.swing.JLabel usernameTxt;
    // End of variables declaration//GEN-END:variables
}
