/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.noscale.ecashier.views;

import com.noscale.ecashier.controllers.MainController;
import com.noscale.ecashier.utilities.Global;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.JFrame;

/**
 *
 * @author rizkikurniawan
 */
public class MainForm extends javax.swing.JFrame {

    private MainController main;
    /**
     * Creates new form HomeForm
     */
    public MainForm(MainController main) {
        initComponents();
        this.main = main;
        productBigPanel.setVisible(false);
        sellBigPanel.setVisible(false);
        supplierBigPanel.setVisible(false);
        reportBigPanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlePanel = new javax.swing.JPanel();
        titleApp = new javax.swing.JLabel();
        userIcon = new javax.swing.JLabel();
        userName = new javax.swing.JLabel();
        userLevel = new javax.swing.JLabel();
        footerPanel = new javax.swing.JPanel();
        bodyPanel = new javax.swing.JPanel();
        productParentPanel = new javax.swing.JPanel();
        productSmallPanel = new javax.swing.JPanel();
        productSmallIcon = new javax.swing.JLabel();
        productSmallLabel = new javax.swing.JLabel();
        productBigPanel = new javax.swing.JPanel();
        productBigIcon = new javax.swing.JLabel();
        productBigLabel = new javax.swing.JLabel();
        sellParentPanel = new javax.swing.JPanel();
        sellSmallPanel = new javax.swing.JPanel();
        sellSmallIcon = new javax.swing.JLabel();
        sellSmallLabel = new javax.swing.JLabel();
        sellBigPanel = new javax.swing.JPanel();
        sellBigIcon = new javax.swing.JLabel();
        sellBigLabel = new javax.swing.JLabel();
        supplierParentPanel = new javax.swing.JPanel();
        supplierSmallPanel = new javax.swing.JPanel();
        supplierSmallIcon = new javax.swing.JLabel();
        supplierSmallLabel = new javax.swing.JLabel();
        supplierBigPanel = new javax.swing.JPanel();
        supplierBigIcon = new javax.swing.JLabel();
        supplierBigLabel = new javax.swing.JLabel();
        reportParentPanel = new javax.swing.JPanel();
        reportSmallPanel = new javax.swing.JPanel();
        reportSmallIcon = new javax.swing.JLabel();
        reportSmallLabel = new javax.swing.JLabel();
        reportBigPanel = new javax.swing.JPanel();
        reportBigIcon = new javax.swing.JLabel();
        reportBigLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titlePanel.setBackground(new java.awt.Color(57, 113, 154));
        titlePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                titlePanelMouseEntered(evt);
            }
        });

        titleApp.setFont(new java.awt.Font("SansSerif", 1, 48)); // NOI18N
        titleApp.setForeground(new java.awt.Color(255, 255, 255));
        titleApp.setText("ECashier");

        userIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/noscale/ecashier/assets/Circled_User_Male_Filled-50.png"))); // NOI18N
        userIcon.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        userIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userIconMouseClicked(evt);
            }
        });

        userName.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        userName.setForeground(new java.awt.Color(255, 255, 255));
        userName.setText("User");

        userLevel.setForeground(new java.awt.Color(255, 255, 255));
        userLevel.setText("Level User");

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titlePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(userIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userName)
                    .addComponent(userLevel))
                .addContainerGap())
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleApp)
                .addContainerGap(462, Short.MAX_VALUE))
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userIcon)
                    .addGroup(titlePanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(userName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userLevel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(titleApp))
        );

        getContentPane().add(titlePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 130));

        footerPanel.setBackground(new java.awt.Color(57, 113, 154));
        footerPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                footerPanelMouseEntered(evt);
            }
        });
        footerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(footerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 710, 130));

        bodyPanel.setBackground(new java.awt.Color(57, 113, 147));
        bodyPanel.setLayout(new java.awt.GridLayout(1, 0));

        productParentPanel.setBackground(new java.awt.Color(57, 113, 147));

        productSmallPanel.setBackground(new java.awt.Color(57, 113, 200));
        productSmallPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                productSmallPanelMouseEntered(evt);
            }
        });
        productSmallPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        productSmallIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/noscale/ecashier/assets/Product-50.png"))); // NOI18N
        productSmallPanel.add(productSmallIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        productSmallLabel.setForeground(new java.awt.Color(255, 255, 255));
        productSmallLabel.setText("Product");
        productSmallPanel.add(productSmallLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        productBigPanel.setBackground(new java.awt.Color(57, 113, 200));
        productBigPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        productBigIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/noscale/ecashier/assets/Product-100_2.png"))); // NOI18N
        productBigPanel.add(productBigIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        productBigLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        productBigLabel.setForeground(new java.awt.Color(255, 255, 255));
        productBigLabel.setText("Product");
        productBigPanel.add(productBigLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        javax.swing.GroupLayout productParentPanelLayout = new javax.swing.GroupLayout(productParentPanel);
        productParentPanel.setLayout(productParentPanelLayout);
        productParentPanelLayout.setHorizontalGroup(
            productParentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productParentPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(productSmallPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(productBigPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        productParentPanelLayout.setVerticalGroup(
            productParentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productParentPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(productSmallPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(productBigPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bodyPanel.add(productParentPanel);

        sellParentPanel.setBackground(new java.awt.Color(57, 113, 147));

        sellSmallPanel.setBackground(new java.awt.Color(57, 113, 200));
        sellSmallPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sellSmallPanelMouseEntered(evt);
            }
        });
        sellSmallPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sellSmallIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/noscale/ecashier/assets/Sell-50.png"))); // NOI18N
        sellSmallPanel.add(sellSmallIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        sellSmallLabel.setForeground(new java.awt.Color(255, 255, 255));
        sellSmallLabel.setText("Sell");
        sellSmallPanel.add(sellSmallLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        sellBigPanel.setBackground(new java.awt.Color(57, 113, 200));
        sellBigPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sellBigIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/noscale/ecashier/assets/Sell-100.png"))); // NOI18N
        sellBigPanel.add(sellBigIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        sellBigLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        sellBigLabel.setForeground(new java.awt.Color(255, 255, 255));
        sellBigLabel.setText("Sell");
        sellBigPanel.add(sellBigLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        javax.swing.GroupLayout sellParentPanelLayout = new javax.swing.GroupLayout(sellParentPanel);
        sellParentPanel.setLayout(sellParentPanelLayout);
        sellParentPanelLayout.setHorizontalGroup(
            sellParentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sellParentPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(sellSmallPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(sellBigPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        sellParentPanelLayout.setVerticalGroup(
            sellParentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sellParentPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(sellSmallPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(sellBigPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bodyPanel.add(sellParentPanel);

        supplierParentPanel.setBackground(new java.awt.Color(57, 113, 147));

        supplierSmallPanel.setBackground(new java.awt.Color(57, 113, 200));
        supplierSmallPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                supplierSmallPanelMouseEntered(evt);
            }
        });
        supplierSmallPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        supplierSmallIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/noscale/ecashier/assets/Shop-50.png"))); // NOI18N
        supplierSmallPanel.add(supplierSmallIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        supplierSmallLabel.setForeground(new java.awt.Color(255, 255, 255));
        supplierSmallLabel.setText("Supplier");
        supplierSmallPanel.add(supplierSmallLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        supplierBigPanel.setBackground(new java.awt.Color(57, 113, 200));
        supplierBigPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        supplierBigIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/noscale/ecashier/assets/Shop-100.png"))); // NOI18N
        supplierBigPanel.add(supplierBigIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        supplierBigLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        supplierBigLabel.setForeground(new java.awt.Color(255, 255, 255));
        supplierBigLabel.setText("Supplier");
        supplierBigPanel.add(supplierBigLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        javax.swing.GroupLayout supplierParentPanelLayout = new javax.swing.GroupLayout(supplierParentPanel);
        supplierParentPanel.setLayout(supplierParentPanelLayout);
        supplierParentPanelLayout.setHorizontalGroup(
            supplierParentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(supplierParentPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(supplierSmallPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(supplierBigPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        supplierParentPanelLayout.setVerticalGroup(
            supplierParentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(supplierParentPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(supplierSmallPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(supplierBigPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bodyPanel.add(supplierParentPanel);

        reportParentPanel.setBackground(new java.awt.Color(57, 113, 147));

        reportSmallPanel.setBackground(new java.awt.Color(57, 113, 200));
        reportSmallPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reportSmallPanelMouseEntered(evt);
            }
        });
        reportSmallPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        reportSmallIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/noscale/ecashier/assets/Check-50.png"))); // NOI18N
        reportSmallPanel.add(reportSmallIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        reportSmallLabel.setForeground(new java.awt.Color(255, 255, 255));
        reportSmallLabel.setText("Report");
        reportSmallPanel.add(reportSmallLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        reportBigPanel.setBackground(new java.awt.Color(57, 113, 200));
        reportBigPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        reportBigIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/noscale/ecashier/assets/Check-100.png"))); // NOI18N
        reportBigPanel.add(reportBigIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        reportBigLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        reportBigLabel.setForeground(new java.awt.Color(255, 255, 255));
        reportBigLabel.setText(" Report");
        reportBigPanel.add(reportBigLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        javax.swing.GroupLayout reportParentPanelLayout = new javax.swing.GroupLayout(reportParentPanel);
        reportParentPanel.setLayout(reportParentPanelLayout);
        reportParentPanelLayout.setHorizontalGroup(
            reportParentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportParentPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(reportSmallPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(reportBigPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        reportParentPanelLayout.setVerticalGroup(
            reportParentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportParentPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(reportSmallPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(reportBigPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bodyPanel.add(reportParentPanel);

        getContentPane().add(bodyPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 710, 160));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void productSmallPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productSmallPanelMouseEntered
        // TODO add your handling code here:
        productBigPanel.setVisible(true);
        productSmallPanel.setVisible(false);
        
        sellBigPanel.setVisible(false);
        sellSmallPanel.setVisible(true);
        
        supplierBigPanel.setVisible(false);
        supplierSmallPanel.setVisible(true);
        
        reportBigPanel.setVisible(false);
        reportSmallPanel.setVisible(true);
        
    }//GEN-LAST:event_productSmallPanelMouseEntered

    private void sellSmallPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sellSmallPanelMouseEntered
        // TODO add your handling code here:
        productBigPanel.setVisible(false);
        productSmallPanel.setVisible(true);
        
        sellBigPanel.setVisible(true);
        sellSmallPanel.setVisible(false);
        
        supplierBigPanel.setVisible(false);
        supplierSmallPanel.setVisible(true);
        
        reportBigPanel.setVisible(false);
        reportSmallPanel.setVisible(true);
        
    }//GEN-LAST:event_sellSmallPanelMouseEntered

    private void supplierSmallPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplierSmallPanelMouseEntered
        // TODO add your handling code here:
        productBigPanel.setVisible(false);
        productSmallPanel.setVisible(true);
        
        sellBigPanel.setVisible(false);
        sellSmallPanel.setVisible(true);
        
        supplierBigPanel.setVisible(true);
        supplierSmallPanel.setVisible(false);
        
        reportBigPanel.setVisible(false);
        reportSmallPanel.setVisible(true);
        
    }//GEN-LAST:event_supplierSmallPanelMouseEntered

    private void reportSmallPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportSmallPanelMouseEntered
        // TODO add your handling code here:
        productBigPanel.setVisible(false);
        productSmallPanel.setVisible(true);
        
        sellBigPanel.setVisible(false);
        sellSmallPanel.setVisible(true);
        
        supplierBigPanel.setVisible(false);
        supplierSmallPanel.setVisible(true);
        
        reportBigPanel.setVisible(true);
        reportSmallPanel.setVisible(false);
    }//GEN-LAST:event_reportSmallPanelMouseEntered

    private void footerPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_footerPanelMouseEntered
        // TODO add your handling code here:
        productBigPanel.setVisible(false);
        productSmallPanel.setVisible(true);
        
        sellBigPanel.setVisible(false);
        sellSmallPanel.setVisible(true);
        
        supplierBigPanel.setVisible(false);
        supplierSmallPanel.setVisible(true);
        
        reportBigPanel.setVisible(false);
        reportSmallPanel.setVisible(true);
    }//GEN-LAST:event_footerPanelMouseEntered

    private void titlePanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titlePanelMouseEntered
        // TODO add your handling code here:
        productBigPanel.setVisible(false);
        productSmallPanel.setVisible(true);
        
        sellBigPanel.setVisible(false);
        sellSmallPanel.setVisible(true);
        
        supplierBigPanel.setVisible(false);
        supplierSmallPanel.setVisible(true);
        
        reportBigPanel.setVisible(false);
        reportSmallPanel.setVisible(true);
    }//GEN-LAST:event_titlePanelMouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        // TODO add your handling code here:
        productBigPanel.setVisible(false);
        productSmallPanel.setVisible(true);
        
        sellBigPanel.setVisible(false);
        sellSmallPanel.setVisible(true);
        
        supplierBigPanel.setVisible(false);
        supplierSmallPanel.setVisible(true);
        
        reportBigPanel.setVisible(false);
        reportSmallPanel.setVisible(true);
    }//GEN-LAST:event_formMouseExited

    private void userIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userIconMouseClicked
        // TODO add your handling code here:
        main.getLoginForm().getController().logout();
        setVisible(false);
        dispose();
    }//GEN-LAST:event_userIconMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JPanel footerPanel;
    private javax.swing.JLabel productBigIcon;
    private javax.swing.JLabel productBigLabel;
    private javax.swing.JPanel productBigPanel;
    private javax.swing.JPanel productParentPanel;
    private javax.swing.JLabel productSmallIcon;
    private javax.swing.JLabel productSmallLabel;
    private javax.swing.JPanel productSmallPanel;
    private javax.swing.JLabel reportBigIcon;
    private javax.swing.JLabel reportBigLabel;
    private javax.swing.JPanel reportBigPanel;
    private javax.swing.JPanel reportParentPanel;
    private javax.swing.JLabel reportSmallIcon;
    private javax.swing.JLabel reportSmallLabel;
    private javax.swing.JPanel reportSmallPanel;
    private javax.swing.JLabel sellBigIcon;
    private javax.swing.JLabel sellBigLabel;
    private javax.swing.JPanel sellBigPanel;
    private javax.swing.JPanel sellParentPanel;
    private javax.swing.JLabel sellSmallIcon;
    private javax.swing.JLabel sellSmallLabel;
    private javax.swing.JPanel sellSmallPanel;
    private javax.swing.JLabel supplierBigIcon;
    private javax.swing.JLabel supplierBigLabel;
    private javax.swing.JPanel supplierBigPanel;
    private javax.swing.JPanel supplierParentPanel;
    private javax.swing.JLabel supplierSmallIcon;
    private javax.swing.JLabel supplierSmallLabel;
    private javax.swing.JPanel supplierSmallPanel;
    private javax.swing.JLabel titleApp;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JLabel userIcon;
    private javax.swing.JLabel userLevel;
    private javax.swing.JLabel userName;
    // End of variables declaration//GEN-END:variables
}
